### ISSUE TITLE
Баг в портфолио

### ISSUE THREAD

**Issue by aseredenko** [Fruit-studio/fs-landings#7]
@flaminisx : "Когда тыкаешь на портфолио, онопоявляется, потом тыкаешь "закрыть", то этот портфолио-итем ведет себя, будто он под маусовером"

**Comment by flaminisx** [comment]
не знаю как, но ты починил

**Comment by aseredenko** [comment]
@flaminisx  Нет, этот баг был сегодня днем. Починил я его только что. Наблюдалось только в хроме под виндой. Реализовал ховер/анховер через jquery. Проблему решило. Работает везде на ура.
